# This file was generated by GoReleaser. DO NOT EDIT.
cask "adaa" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "8867319cf006fe37c920fbfd47bdeb19094c66a6abfcf2aedab0b66562e86b12"
      url "https://github.com/getadaa/cli/releases/download/v#{version}/adaa_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9b799ab2c3e10bd583e6edbf4c081cdb085496d4d768432760d9965ab947277c"
      url "https://github.com/getadaa/cli/releases/download/v#{version}/adaa_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5d66e560a3ef996487a82f87f9d8d62836e8fe7e483720859cdda3b7f32512f1"
      url "https://github.com/getadaa/cli/releases/download/v#{version}/adaa_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c0fe648cc6520c3c587a1789b3c72b98544552920ff87912719d66ac08576335"
      url "https://github.com/getadaa/cli/releases/download/v#{version}/adaa_#{version}_linux_amd64.tar.gz"
    end
  end

  name "adaa"
  desc "Run your company's IT from the terminal"
  homepage "https://adaa.no"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "adaa"
  bash_completion "completions/adaa.bash"
  fish_completion "completions/adaa.fish"
  zsh_completion "completions/_adaa"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/adaa"]
    end
  end

  # No zap stanza required
end
