# This file was generated by GoReleaser. DO NOT EDIT.
cask "adaa" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "68c06b76c7f9502d2b798e5741b743f6bd631b84ad0ff87b402659490abcd96d"
      url "https://github.com/getadaa/cli/releases/download/v#{version}/adaa_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2ffd0ef23360eee81cdae9632752c30e42ae97f2db92885b11a348d8a3e32a5e"
      url "https://github.com/getadaa/cli/releases/download/v#{version}/adaa_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f01ce03bd15f24671b05bad87cb3163fd44e8830320652c72de484ee74995a82"
      url "https://github.com/getadaa/cli/releases/download/v#{version}/adaa_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "23fd9d24a70228bcc443989e71519e86fc9c8cce0191edd5ada3a72815c3290c"
      url "https://github.com/getadaa/cli/releases/download/v#{version}/adaa_#{version}_linux_amd64.tar.gz"
    end
  end

  name "adaa"
  desc "Run your company's IT from the terminal"
  homepage "https://adaa.no"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "adaa"
  bash_completion "completions/adaa.bash"
  fish_completion "completions/adaa.fish"
  zsh_completion "completions/_adaa"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/adaa"]
    end
  end

  # No zap stanza required
end
